### ISSUE TITLE
Hi 🙋🏼‍♂️

### ISSUE THREAD

**Issue by wcandillon** [mateoguzmana/react-native-clocks#3]
Let us know if you have any/questions request for us. We weren't sure how to find you on social media 😊

**Comment by mateoguzmana** [comment]
@wcandillon will do! it's been a couple of weeks since I don't play with Skia but I've been following your recent updates and I plan to try out the new UI thread rendering for https://github.com/mateoguzmana/react-native-fiesta as I was experiencing some laggy renders there. Thanks for reaching out :D
